"""add progress and lesson completions tables

Revision ID: d51610573516
Revises: ffcae5cbe8b3
Create Date: 2026-02-13 09:16:17.312838
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d51610573516"
down_revision: str | None = "ffcae5cbe8b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_accessed_lesson_id", sa.UUID(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_accessed_lesson_id"], ["lessons.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "course_id", name="uq_progress_user_course"),
    )
    op.create_index("idx_progress_course", "progress", ["course_id"], unique=False)
    op.create_index("idx_progress_user", "progress", ["user_id"], unique=False)
    op.create_index(op.f("ix_progress_course_id"), "progress", ["course_id"], unique=False)
    op.create_index(op.f("ix_progress_user_id"), "progress", ["user_id"], unique=False)
    op.create_table(
        "lesson_completions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("progress_id", sa.UUID(), nullable=False),
        sa.Column("lesson_id", sa.UUID(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["progress_id"], ["progress.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("progress_id", "lesson_id", name="uq_completion_progress_lesson"),
    )
    op.create_index(
        "idx_completion_progress", "lesson_completions", ["progress_id", "lesson_id"], unique=False
    )
    op.create_index(
        op.f("ix_lesson_completions_progress_id"),
        "lesson_completions",
        ["progress_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lesson_completions_progress_id"), table_name="lesson_completions")
    op.drop_index("idx_completion_progress", table_name="lesson_completions")
    op.drop_table("lesson_completions")
    op.drop_index(op.f("ix_progress_user_id"), table_name="progress")
    op.drop_index(op.f("ix_progress_course_id"), table_name="progress")
    op.drop_index("idx_progress_user", table_name="progress")
    op.drop_index("idx_progress_course", table_name="progress")
    op.drop_table("progress")
    # ### end Alembic commands ###
